### PR TITLE
Getoptify options parsing. Allow hex code for RGB color setting.

### PR DESCRIPTION
**Pull request by sebdel**
Hello,

I'm aware that this is a big commit, I would totally understand if you're not interested in commiting it :)

What it brings to the table:
- it makes msiklm more in line with other cli on linux
- options can be passed in any order
- colors can be set by using hex code (of the form '0xRRGGBB')

FYI, I'm developing a graphical frontend on this base. You can checkout msiklm_ui in my repos.

BR
Seb

### CODE REVIEW

**Comment by Gibtnix** [comment]
Thanks for your PR, I'll take a look at your code soon and will come back later to it.

**Comment by Gibtnix** [comment]
I finally found the time to review your code... first of all I generally appreciate your work, however I decided that I won't commit it this way into the master branch. I fully agree with you that your modifications make the program more similar to other Linux/Unix command line programs, however I personally prefer to keep simple things simple: simply concatenating the respective colors and optionally adding intensity and mode is much more intuitive here, at least from my point of view. Further the autostart functionality will be broken with your changes, as well as setting the color for more than three zones is not supported any more. I will think of extending some things in my code (e.g. support hex codes during color parsing), but I would like to keep most parts the way they currently are.

**Comment by sebdel** [comment]
Understood. I figured it was not really going in the direction you had chosen. I submitted it just in case but I'll close that PR.
Thanks for your time :)

**Comment by Gibtnix** [comment]
Thanks for your work anyway, I might come back for at, at least for the hex code support :-)

**Pull request closed without merging**
